# Generated by Django 4.1.7 on 2023-03-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "update_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                ("isCompleted", models.BooleanField(default=False)),
            ],
        ),
    ]
