# Generated by Django 4.1.7 on 2023-03-22 20:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("todo", "0002_todo_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="Description",
        ),
    ]
